### PR TITLE
Make composer outdated empty

### PR DESCRIPTION
**Pull request by greg0ire**
Let's try to allow Twig 2, see if the build still passes.

### CODE REVIEW

**Comment by greg0ire** [comment]
Looks like sf 3.0 is not compatible with phpunit 6 but does not say so?

**Comment by yannickl88** [comment]
yeah, symfony has some test cases which still extend the old unit tests. Which have been removed in 6 in favor of the namespaced one.

**Comment by greg0ire** [comment]
What should we do? Stop testing 3.0? Is it still supported?

**Comment by yannickl88** [comment]
correct :smile:, 3.0 is no longer supported and 3.1 will be EOL in July, so for travis we can bump it to 3.2. PHPUnit 6 can be supported once we bump the requirements to 3.2 I guess.

**Pull request merged**
